name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: Deploy to EC2
        run: |
          sshpass -p ${{ secrets.EC2_PASSWORD }} ssh -o StrictHostKeyChecking=no -p <your_ssh_port> <your_username>@<your_host> 'cd /var/www/writehome && sudo cp -r * /var/www/writehome && sudo chown -R www-data:www-data /var/www/writehome && sudo chmod -R 755 /var/www/writehome'
