name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: jakejarvis/ssh-action@v2.6.0
        with:
          host: 3.28.231.87
          username: dev
          password: dev@2023
          script: |
            cd /var/www/writehome
            sudo cp -r * /var/www/writehome
            sudo chown -R www-data:www-data /var/www/writehome
            sudo chmod -R 755 /var/www/writehome
