name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client and rsync
        run: sudo apt-get install -y sshpass rsync

      - name: Deploy to EC2
        run: |
          sshpass -p "dev@2023" rsync -e "ssh -o StrictHostKeyChecking=no -p 22" -r ./path/to/local/files/ dev@3.28.231.87:/var/www/writehome
