name: Laravel

on:
  push:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd ${{ github.workspace }}/WriteHomes
          composer install --no-interaction --no-progress --prefer-dist

      - name: Generate key
        run: |
          cd ${{ github.workspace }}/WriteHomes
          php artisan key:generate

      - name: Directory Permissions
        run: |
          cd ${{ github.workspace }}/WriteHomes
          chmod -R 777 storage bootstrap/cache

      - name: Deploy to /var/www/writehome
        run: |
          sudo cp -R ${{ github.workspace }}/WriteHomes/. /var/www/writehome
          sudo chown -R www-data:www-data /var/www/writehome
          sudo chmod -R 755 /var/www/writehome
