name: Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: cd WriteHomes && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: cd WriteHomes && php artisan key:generate
    - name: Directory Permissions
      run: cd WriteHomes && chmod -R 777 storage bootstrap/cache
